"""add_source_constraint

Revision ID: 1e26b8ed3ab2
Revises: 
Create Date: 2026-04-28 12:00:39.761398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e26b8ed3ab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('source', sa.String(length=64), server_default='2gis', nullable=False))
    op.drop_index(op.f('ix_branches_gis_branch_id'), table_name='branches')
    op.create_index(op.f('ix_branches_gis_branch_id'), 'branches', ['gis_branch_id'], unique=False)
    op.create_unique_constraint('uq_gis_branch_id_source', 'branches', ['gis_branch_id', 'source'])
    op.add_column('search_tasks', sa.Column('source', sa.String(length=64), server_default='2gis', nullable=False))
    op.alter_column('search_tasks', 'query',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_tasks', 'query',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('search_tasks', 'source')
    op.drop_constraint('uq_gis_branch_id_source', 'branches', type_='unique')
    op.drop_index(op.f('ix_branches_gis_branch_id'), table_name='branches')
    op.create_index(op.f('ix_branches_gis_branch_id'), 'branches', ['gis_branch_id'], unique=True)
    op.drop_column('branches', 'source')
    # ### end Alembic commands ###
