"""Add claude columns to task_topics_cache

Revision ID: 2af9e15768ec
Revises: 1e26b8ed3ab2
Create Date: 2026-05-05 10:10:25.258085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2af9e15768ec'
down_revision: Union[str, Sequence[str], None] = '1e26b8ed3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_topics_cache', sa.Column('problems', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('task_topics_cache', sa.Column('priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('task_topics_cache', sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_topics_cache', 'insights')
    op.drop_column('task_topics_cache', 'priorities')
    op.drop_column('task_topics_cache', 'problems')
    # ### end Alembic commands ###
