"""Add category and city to branch

Revision ID: 941d938a4e6e
Revises: 2af9e15768ec
Create Date: 2026-05-05 15:37:37.264288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941d938a4e6e'
down_revision: Union[str, Sequence[str], None] = '2af9e15768ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('branches', sa.Column('category', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_branches_category'), 'branches', ['category'], unique=False)
    op.create_index(op.f('ix_branches_city'), 'branches', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_city'), table_name='branches')
    op.drop_index(op.f('ix_branches_category'), table_name='branches')
    op.drop_column('branches', 'category')
    op.drop_column('branches', 'city')
    # ### end Alembic commands ###
